from django.db import models

class Category(models.Model):
    id = models.IntegerField(primary_key='true')
    m_cat_id = models.CharField(max_length=24)
    name = models.CharField(max_length=255)
    bucket = models.CharField(max_length=50)
    status = models.CharField(max_length=3)
    billing_rate = models.FloatField()
    billing_type = models.CharField(max_length=3)
    is_children_category = models.IntegerField()
    is_marketing = models.IntegerField()
    type = models.CharField(max_length=11, blank=True, null=True)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()
    deleted_at = models.DateTimeField(blank=True, null=True)
    pricing_format = models.CharField(max_length=255)
    pricing_format_type = models.CharField(max_length=255)
    token_amount_percentage = models.FloatField()
    max_token_amount = models.IntegerField()
    available_view = models.CharField(max_length=255)
    default_view_mobile = models.CharField(max_length=255)
    default_view_app = models.CharField(max_length=255)
    default_view = models.CharField(max_length=255)
    what_next_image_path = models.CharField(max_length=255)
    what_next_url = models.CharField(max_length=255)
    banner_image_path = models.CharField(max_length=255)
    banner_url = models.CharField(max_length=255)
    thumbnail_image_path = models.CharField(max_length=255)
    thumbnail_url = models.CharField(max_length=255)
    background_image_path = models.CharField(max_length=255)
    background_url = models.CharField(max_length=255)
    icon_image_path = models.CharField(max_length=255)
    icon_url = models.CharField(max_length=255)
    order_flow_id = models.IntegerField()
    buyer_guide_url = models.CharField(max_length=255)
    seo_url = models.CharField(max_length=255)
    page_title = models.CharField(max_length=255)
    meta_keyword = models.CharField(max_length=510)
    meta_description = models.CharField(max_length=1020)
    context = models.CharField(max_length=4)
    subscription_fee_months_1 = models.FloatField()
    subscription_fee_months_3 = models.FloatField()
    subscription_fee_months_12 = models.FloatField()
    enterprise_subscription_months_1 = models.FloatField()
    enterprise_subscription_months_3 = models.FloatField()
    enterprise_subscription_months_12 = models.FloatField()
    auto_renewal_type = models.CharField(max_length=9)
    total_mkt_spent = models.FloatField()
    sort_order = models.IntegerField()
    max_dfc_percentage = models.FloatField()
    max_dfc_value = models.IntegerField()
    available_modules = models.TextField(blank=True, null=True)
    display_on_root = models.CharField(max_length=1)
    no_of_filter_display = models.IntegerField()
    fcts_condition = models.TextField(blank=True, null=True)
    source_category_id = models.IntegerField(blank=True, null=True)
    available_modules_new = models.TextField(blank=True, null=True)
    is_visible_on_seller_onboarding = models.IntegerField()
    is_visible_on_listing_onboarding = models.IntegerField()
    is_visible_on_shop_page = models.IntegerField()
    is_visible_on_home_page = models.IntegerField()
    grouping_context = models.CharField(max_length=255, blank=True, null=True)
    is_condition = models.TextField(blank=True, null=True)
    is_mmyt = models.IntegerField()
    is_placeholder = models.IntegerField()
    is_example_placeholder = models.CharField(max_length=255)
    is_tooltip = models.CharField(max_length=255)
    allow_bulk_listing = models.TextField(blank=True, null=True)
    icon_class = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'category'

class CouponApprOnListing(models.Model):
    coupon_id = models.CharField(max_length=40)
    coupon_code = models.CharField(max_length=40)
    listing_id = models.CharField(max_length=40)
    lid = models.CharField(max_length=40)
    discount = models.IntegerField()
    dfc = models.IntegerField()
    category_id = models.CharField(max_length=40)
    status = models.CharField(max_length=35)
    category_name = models.CharField(max_length=60)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()
    end_date = models.DateTimeField()
    max_dfc_value = models.FloatField()
    dfc_percentage = models.FloatField()
    max_dfc_percentage = models.FloatField()
    difference = models.FloatField()
    exceeded = models.CharField(max_length=255)
    selling_price = models.FloatField()
    total_payout = models.FloatField()

    class Meta:
        managed = False
        db_table = 'coupon_appr_on_listing'

class Users(models.Model):
    email = models.CharField(unique=True, max_length=255)
    handle_name = models.CharField(max_length=128, blank=True, null=True)
    password = models.CharField(max_length=255)
    permissions = models.TextField(blank=True, null=True)
    activated = models.IntegerField()
    activation_code = models.CharField(max_length=255, blank=True, null=True)
    activated_at = models.DateTimeField(blank=True, null=True)
    last_login = models.DateTimeField(blank=True, null=True)
    persist_code = models.CharField(max_length=255, blank=True, null=True)
    reset_password_code = models.CharField(max_length=255, blank=True, null=True)
    first_name = models.CharField(max_length=255, blank=True, null=True)
    last_name = models.CharField(max_length=255, blank=True, null=True)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()
    email_verified = models.IntegerField()
    gender = models.CharField(max_length=7)
    status = models.CharField(max_length=13)
    language_id = models.IntegerField()
    address1 = models.CharField(max_length=500, blank=True, null=True)
    address2 = models.CharField(max_length=500, blank=True, null=True)
    city = models.CharField(max_length=64, blank=True, null=True)
    city_id = models.IntegerField(blank=True, null=True)
    state = models.CharField(max_length=64, blank=True, null=True)
    state_id = models.IntegerField(blank=True, null=True)
    zip = models.CharField(max_length=10, blank=True, null=True)
    alt_email = models.CharField(max_length=100, blank=True, null=True)
    home_phone = models.CharField(max_length=16, blank=True, null=True)
    mobile_phone = models.CharField(max_length=16, blank=True, null=True)
    preferred_method = models.CharField(max_length=5)
    emergency_contact_person = models.CharField(max_length=100, blank=True, null=True)
    emergency_contact_person_phone = models.CharField(max_length=16, blank=True, null=True)
    reset_password_code_expiry = models.DateTimeField(blank=True, null=True)
    phone_verified = models.IntegerField()
    pan_verified = models.IntegerField()
    vat_verified = models.IntegerField()
    facebook_photo_url = models.CharField(max_length=128, blank=True, null=True)
    profile_photo_path = models.CharField(max_length=128, blank=True, null=True)
    facebook_id = models.CharField(max_length=40, blank=True, null=True)
    vendor_id = models.IntegerField(blank=True, null=True)
    droom_id = models.CharField(unique=True, max_length=12, blank=True, null=True)
    viewing_shipping = models.TextField(blank=True, null=True)
    schedule = models.TextField(blank=True, null=True)
    payment_option = models.TextField(blank=True, null=True)
    banking_details = models.TextField(blank=True, null=True)
    verified_status = models.CharField(max_length=32, blank=True, null=True)
    seller_type = models.CharField(max_length=32, blank=True, null=True)
    vehicle_types = models.TextField(blank=True, null=True)
    authorized_dealer_for = models.TextField(blank=True, null=True)
    pan_number = models.CharField(max_length=32, blank=True, null=True)
    vat_number = models.CharField(max_length=32, blank=True, null=True)
    business_description = models.TextField(blank=True, null=True)
    dealership_photos = models.TextField(blank=True, null=True)
    verified_date = models.TextField(blank=True, null=True)
    verify_application_date = models.TextField(blank=True, null=True)
    deleted_at = models.DateTimeField(blank=True, null=True)
    watchlist_ending_notification = models.IntegerField()
    rejected_offer_notification = models.IntegerField()
    received_offer_notification = models.IntegerField()
    commit_to_buy_notification = models.IntegerField()
    payment_received = models.TextField(blank=True, null=True)
    persist_code1 = models.CharField(max_length=255, blank=True, null=True)
    persist_code2 = models.CharField(max_length=255, blank=True, null=True)
    persist_code3 = models.CharField(max_length=255, blank=True, null=True)
    persist_code4 = models.CharField(max_length=255, blank=True, null=True)
    is_offline = models.IntegerField(blank=True, null=True)
    is_suspended = models.IntegerField(blank=True, null=True)
    last_suspended_date = models.DateField()
    new_status = models.IntegerField(blank=True, null=True)
    new_seller_type = models.IntegerField(blank=True, null=True)
    source = models.CharField(max_length=255, blank=True, null=True)
    suspension_count = models.IntegerField(blank=True, null=True)
    suspended_from = models.DateTimeField(blank=True, null=True)
    suspended_to = models.DateTimeField(blank=True, null=True)
    offline_from = models.DateTimeField(blank=True, null=True)
    offline_to = models.DateTimeField(blank=True, null=True)
    campaign = models.TextField(blank=True, null=True)
    login_code = models.CharField(max_length=100, blank=True, null=True)
    landmark = models.CharField(max_length=256)
    return_policy = models.CharField(max_length=50, blank=True, null=True)
    return_policy_option = models.CharField(max_length=20, blank=True, null=True)
    rto_service = models.IntegerField(blank=True, null=True)
    rto_service_type = models.CharField(max_length=10, blank=True, null=True)
    rto_service_price = models.IntegerField(blank=True, null=True)
    test_drive = models.IntegerField(blank=True, null=True)
    test_drive_price = models.IntegerField(blank=True, null=True)
    otp_verified = models.CharField(max_length=1)
    handle_name_alias = models.CharField(max_length=128, blank=True, null=True)
    handle_name_old = models.CharField(max_length=128, blank=True, null=True)
    subscription_notification = models.IntegerField()
    login_count = models.IntegerField()
    latitude = models.FloatField()
    longitude = models.FloatField()
    user_type = models.CharField(max_length=20)
    user_status = models.CharField(max_length=20)
    t_email = models.IntegerField()
    t_sms = models.IntegerField()
    m_email = models.IntegerField()
    m_sms = models.IntegerField()
    register_source = models.CharField(max_length=50)
    is_droom_user = models.CharField(max_length=1)
    garbage_user = models.IntegerField()
    location = models.CharField(max_length=50, blank=True, null=True)
    middle_name = models.CharField(max_length=100, blank=True, null=True)
    company_name = models.CharField(max_length=50)
    contact_email = models.CharField(max_length=255)
    aadhar_number = models.CharField(max_length=15, blank=True, null=True)
    aadhar_verification = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'users'
        unique_together = (('vendor_id', 'email'),)

class Vendors(models.Model):
    vendor_name = models.CharField(max_length=255, blank=True, null=True)
    email = models.CharField(unique=True, max_length=255)
    alt_email = models.CharField(max_length=255, blank=True, null=True)
    invite_code = models.CharField(max_length=255, blank=True, null=True)
    activated_at = models.DateTimeField(blank=True, null=True)
    email_verified = models.IntegerField()
    status = models.CharField(max_length=8)
    seller_plan = models.CharField(max_length=7)
    language_id = models.IntegerField()
    address1 = models.CharField(max_length=100, blank=True, null=True)
    address2 = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=64, blank=True, null=True)
    city_id = models.IntegerField(blank=True, null=True)
    state = models.CharField(max_length=64, blank=True, null=True)
    state_id = models.IntegerField(blank=True, null=True)
    zip = models.CharField(max_length=10, blank=True, null=True)
    work_phone = models.CharField(max_length=16, blank=True, null=True)
    mobile_phone = models.CharField(max_length=16, blank=True, null=True)
    emergency_contact_person = models.CharField(max_length=100, blank=True, null=True)
    emergency_contact_person_phone = models.CharField(max_length=16, blank=True, null=True)
    phone_verified = models.IntegerField()
    pan_verified = models.IntegerField()
    vat_verified = models.IntegerField()
    seller_status = models.CharField(max_length=32, blank=True, null=True)
    seller_type = models.CharField(max_length=32, blank=True, null=True)
    vehicle_types = models.TextField(blank=True, null=True)
    authorized_dealer_for = models.TextField(blank=True, null=True)
    dealer_for = models.CharField(max_length=12, blank=True, null=True)
    pan_number = models.CharField(max_length=32, blank=True, null=True)
    vat_number = models.CharField(max_length=32, blank=True, null=True)
    business_description = models.TextField(blank=True, null=True)
    dealership_photos = models.TextField(blank=True, null=True)
    logo_path = models.CharField(max_length=255, blank=True, null=True)
    subscription_type = models.CharField(max_length=32, blank=True, null=True)
    subscription_start = models.DateTimeField(blank=True, null=True)
    subscription_end = models.DateTimeField(blank=True, null=True)
    verified_date = models.DateTimeField(blank=True, null=True)
    application_date = models.DateTimeField(blank=True, null=True)
    deleted_at = models.DateTimeField(blank=True, null=True)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()
    subscription_notification_count = models.IntegerField(blank=True, null=True)
    grace_subscription = models.IntegerField(blank=True, null=True)
    seller_current_status = models.IntegerField(blank=True, null=True)
    suspended_dmp_status = models.IntegerField(blank=True, null=True)
    release_dmp_suspended_payment = models.IntegerField()
    release_suspended_payment = models.IntegerField()
    suspended_dmp_reason = models.CharField(max_length=1000, blank=True, null=True)
    primary_category = models.CharField(max_length=128, blank=True, null=True)
    is_sell_online = models.IntegerField(blank=True, null=True)
    is_digital_catalog = models.IntegerField(blank=True, null=True)
    is_authorized_dealer = models.IntegerField()
    last_date_marked_authorized_dealer = models.DateField()
    authorized_dealer_marked_by = models.CharField(max_length=255)
    authorized_dealer_makes = models.CharField(max_length=255)
    authorized_dealer_certificate = models.CharField(max_length=255)
    mapped_odn = models.CharField(max_length=255)
    odn_marked_by = models.CharField(max_length=255)
    is_top_rated_seller = models.IntegerField(blank=True, null=True)
    last_date_marked_top_rated = models.DateField()
    top_rated_marked_by = models.CharField(max_length=255)
    cp_id = models.IntegerField(blank=True, null=True)
    tnc_popup = models.IntegerField(blank=True, null=True)
    welcome_coupons = models.IntegerField(blank=True, null=True)
    subscription_payment_id = models.CharField(max_length=255, blank=True, null=True)
    subscription_grade = models.CharField(max_length=8, blank=True, null=True)
    grace_period_start = models.CharField(max_length=1)
    enable_auto_renew = models.CharField(max_length=1)
    on_expiration = models.CharField(max_length=6, blank=True, null=True)
    trs_start_date = models.DateField(blank=True, null=True)
    trs_end_date = models.DateField(blank=True, null=True)
    droom_id = models.CharField(unique=True, max_length=255, blank=True, null=True)
    is_direct_sales_agent = models.IntegerField()
    last_date_marked_direct_sales_agent = models.DateField()
    direct_sales_agent_marked_by = models.CharField(max_length=100)
    address_proof = models.CharField(max_length=100, blank=True, null=True)
    address_proof_files = models.TextField(blank=True, null=True)
    location = models.CharField(max_length=50, blank=True, null=True)
    landmark = models.CharField(max_length=50, blank=True, null=True)
    identity_verified = models.IntegerField()
    address_verified = models.IntegerField()
    account_verified = models.IntegerField()
    is_address_rejected = models.IntegerField()
    is_identity_rejected = models.IntegerField()
    kyc_status = models.IntegerField()
    kyc_verified_at = models.DateTimeField(blank=True, null=True)
    dsa_data = models.CharField(max_length=255, blank=True, null=True)
    dsa_status = models.IntegerField(blank=True, null=True)
    seller_mode = models.CharField(max_length=50, blank=True, null=True)
    enterprise_user = models.IntegerField()
    enterprise_type = models.CharField(max_length=50)
    subscription_package = models.CharField(max_length=30, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'vendors'

class CouponMapping(models.Model):
    coupon_id = models.CharField(max_length=255)
    listing_id = models.IntegerField()
    promotion_name = models.CharField(max_length=255)
    code = models.CharField(max_length=255)
    status = models.CharField(max_length=1)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()
    start_time = models.CharField(max_length=255)
    end_time = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'coupon_mapping'




